### ISSUE TITLE
tracking: Migrate all classes running persistent tasks to use `BackgroundService`

### ISSUE THREAD

**Issue by llucax** [frequenz-floss/frequenz-sdk-python#633]
### What's needed?

We have quite a few classes that spawn persistent tasks which could benefit from inheriting from `BackgroundService`, so they have a common interface, they can be used as context managers and have some of the task bookkeeping done by `BackgroundService`.

List of classes that might need migrating (create tasks):

- [ ] `ComponentMetricsResamplingActor`  (is an actor but it also create some extra tasks, not using the facilities of `BackgroundService`, this might also need #632)
- [ ] `MicrogridApiSource` (data sourcing actor)
- [ ] `PowerDistributingActor` (is an actor but it also create some extra tasks, not using the facilities of `BackgroundService`, this might also need #632)
  - [ ] `BatteryPoolStatus` (power distributing actor)
  - [ ] `BatteryStatusTracker` (power distributing actor)
- [ ] `MicrogridGrpcClient` (microgrid API)
- Timeseries
  - [ ] `FormulaEngine` / `FormulaEngine3Phase`
  - [ ] `Resampler` (or the helper classes, might need some refactoring)
- [ ] `BatteryPool`
  - [ ] `SendOnUpdate`
- [ ] `EVChargerPool`
  - [ ] `BoundsSetter`
  - [ ] `StateTracker`

**Note:** There are some classes that only manage one task, and communicate via channels, which probably make them a better target for an `Actor` than a `BackgroundService` even.

### Proposed solution

Simply migrate the classes to inherit from `BackgroundService` (or `Actor` where appropriate).

### Additional context

This should fix many issues in tests about dangling tasks.

- #119
